language: node_js
os: linux
sudo: required
dist: trusty
addons:
  sources:
    - ubuntu-toolchain-r-test
  apt:
    packages:
      - gcc-4.8
      - g++-4.8
      - xvfb
node_js:
  - '6'
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
  - sleep 3

env:
  - CXX=g++-4.8

notifications:
  email:
    recipients:
      - sebastien.jourdain@kitware.com
      - ken.martin@kitware.com
      - scott.wittenburg@kitware.com
    on_success: change
    on_failure: always

cache:
  directories:
    - node_modules
    - Documentation/build-tmp

script:
  - npm install
  - npm run build:release
  - npm run test:travis
  - git config --global user.name "Travis CI"
  - git config --global user.email "sebastien.jourdain@kitware.com"
  - export GIT_PUBLISH_URL=https://${GH_TOKEN}@github.com/Kitware/vtk-js.git
  - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run doc:publish; fi

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
