language: node_js
os: linux
sudo: required
dist: trusty
group: travis_lts
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgif-dev
  - npm install -g canvas@1.6.9
addons:
  chrome: stable
node_js:
  - '8'
notifications:
  email:
    recipients:
      - sebastien.jourdain@kitware.com
      - ken.martin@kitware.com
    on_success: change
    on_failure: always

cache:
  directories:
    - node_modules
    - Documentation/build-tmp

script:
  - if [ "$TRAVIS_EVENT_TYPE" == "pull_request" ]; then ./Utilities/ci/travis-test.sh; fi
  - if [ "$TRAVIS_EVENT_TYPE" == "push" ] && [ "$TRAVIS_BRANCH" == "master" ]; then ./Utilities/ci/travis-release.sh; fi
